// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmob62jMLkopLR3ZdnWT9EpzgIOsYBQmg',
    appId: '1:750841257618:android:4d2fa0dcae83c74036904b',
    messagingSenderId: '750841257618',
    projectId: 'papers-sci',
    storageBucket: 'papers-sci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwIx6RknRYuMUkFaDFL6F4R5gYuMebnE',
    appId: '1:750841257618:ios:fdf00910ae525c0536904b',
    messagingSenderId: '750841257618',
    projectId: 'papers-sci',
    storageBucket: 'papers-sci.firebasestorage.app',
    iosBundleId: 'com.sci.sci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrwIx6RknRYuMUkFaDFL6F4R5gYuMebnE',
    appId: '1:750841257618:ios:fdf00910ae525c0536904b',
    messagingSenderId: '750841257618',
    projectId: 'papers-sci',
    storageBucket: 'papers-sci.firebasestorage.app',
    iosBundleId: 'com.sci.sci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs6pN_dURtfl_qjEX5fwGrq3mSC7-Fd4g',
    appId: '1:750841257618:web:5329a74c739366dd36904b',
    messagingSenderId: '750841257618',
    projectId: 'papers-sci',
    authDomain: 'papers-sci.firebaseapp.com',
    storageBucket: 'papers-sci.firebasestorage.app',
  );
}
